### ISSUE TITLE
萌新求教

### ISSUE THREAD

**Issue by LeonidasZhak** [inFaaa/PKU-Beamer-Theme#1]
抱歉求教大佬，入手beamer的小白在设置了自己的section以后，我自己设置了7个section，而且section名字都是英文，但是在我最后编译后，最上面的目录栏里始终会出现“参考文献”这个section名字（事实上我的整个tex文件里面都没有‘参考文献’这4个字，以及对应的超链接可以直接点到我bib的部分，想请问下大佬这是为什么呀？是模板自带识别bib然后就会自动生成‘参考文献“这4字中文名吗？我又没有办法改掉呢？谢谢大佬！

**Comment by inFaaa** [comment]
我这边试了一下，并没有出现您说的现象诶。您可以提供下tex文件看一下。
