### ISSUE TITLE
beamer 播放 bug

### ISSUE THREAD

**Issue by KarryRen** [inFaaa/PKU-Beamer-Theme#3]
作者您好，我发现咱们的 beamer 播放的时候上沿有一条明显的白边，请问可以调整吗？

**Comment by inFaaa** [comment]
我试了一下暂时没办法调整诶。

**Comment by KarryRen** [comment]
好的 感谢您～

**Comment by inFaaa** [comment]
没关系，后续等我稍微空闲一些，我调整下有新的版本再release哈。应该不是大问题。
